"""Criteria used by probes. Importing this module registers all of them."""

from hydroturing.criteria.base import (  # noqa: F401
    CRITERIA,
    FAIL,
    PAIRED,
    PASS,
    CriterionIncompatibleError,
    CriterionResult,
    criterion,
    depth_series,
    get,
    is_paired,
    make_window,
    segments,
)
from hydroturing.criteria import (  # noqa: F401,E402
    closure,
    bounds,
    coherence,
    degeneracy,
    event_water_closure,
    exchange,
    groundwater,
    human,
    limits,
    radiation,
    rating,
    regime,
    response,
    routing_lag,
    storage,
    stress,
    symmetry,
    thermal,
    uniform_flow,
    wave_celerity,
)

__all__ = [
    "CRITERIA",
    "PAIRED",
    "CriterionResult",
    "CriterionIncompatibleError",
    "PASS",
    "FAIL",
    "criterion",
    "depth_series",
    "get",
    "is_paired",
    "make_window",
    "segments",
]
